remote_fs:
  resource_group: Cloudbenchmark
  location: westeurope
  managed_disks:
    premium: false
    disk_size_gb: 103
    disk_names:
    - p30-disk0a
    - p30-disk0b
    - p30-disk1a
    - p30-disk1b
  storage_clusters:
    gadgetcluster:
      hostname_prefix: gadgetcluster
      ssh:
        username: shipyard
      file_server:
        mount_options:
        - noatime
        - nodiratime
        mountpoint: /data
        server_options:
          glusterfs:
            performance.cache-size: 1 GB
            transport: tcp
            volume_name: gv0
            volume_type: distributed
        type: glusterfs
      virtual_network:
        address_space: 10.0.0.0/16
        existing_ok: true
        name: gadget_vnet
        subnet:
          address_prefix: 10.0.0.0/24
          name: gadget-subnet
      network_security:
        ssh:
        - '*'
      public_ip:
        enabled: true
        static: false
      accelerated_networking: true
      vm_count: 2
      vm_size: STANDARD_F16S
      vm_disk_map:
        '0':
          disk_array:
          - p30-disk0a
          - p30-disk1a
          filesystem: btrfs
          raid_level: 0
        '1':
          disk_array:
          - p30-disk0b
          - p30-disk1b
          filesystem: btrfs
          raid_level: 0
