
job_specifications:
  - auto_complete: true
    id: mpiyello
    tasks:
      - docker_image: mdavezac/mpihello:0.0.3
        multi_instance:
          num_instances: pool_current_dedicated
        command: /mnt/resource/batch/tasks/mounts/gadgetcluster/script.sh

    allow_run_on_missing_image: true
    remove_container_after_exit: true
