pool_specification:
  id: gadget-multinode
  vm_configuration:
    platform_image:
      offer: CentOS-HPC
      publisher: OpenLogic
      sku: '7.3'
  vm_count:
    dedicated: 2
    low_priority: 0
  vm_size: STANDARD_A8
  inter_node_communication_enabled: true
  ssh:
    username: root
